repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        stages: [push]
        language: system
        entry: pylint
        types: [python]
        args:
        -   --rcfile=.pylintrc
