repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        stages: [commit]
        language: system
        entry: pylint
        types: [python]
        args:
        - --rcfile=.pylintrc
default_language_version:
  python: python3.9
default_stages: [commit]