repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        stages: [push]
        language: system
        entry: pylint --rcfile=.pylintrc `ls -R|grep .py$|xargs`
        types: [python]
