version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/discord/
hooks:
  BeforeInstall:
    - location: scripts/kill.sh
    - location: scripts/cleanup.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/change_permissions.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/setup.sh
    - location: scripts/start.sh
      timeout: 300
      runas: ubuntu
